"""Rebuild the manually authored, source-reviewed bank. No external enrichment."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
units, questions = [], []
current = None

def unit(pages, title, kind='concept'):
    global current
    if isinstance(pages, int): pages = [pages]
    chapter = 'women' if max(pages) <= 39 else 'population'
    current = dict(id=f'{chapter}-u{sum(u["chapter_id"] == chapter for u in units)+1:03}', chapter_id=chapter,
                   title=title, source_pages=pages, kind=kind, recall_points=[], importance='high', related_unit_ids=[])
    units.append(current)

def q(prompt, answer, category='concept', quick=False, scope='unit', note=''):
    chapter=current['chapter_id']
    obj=dict(id=f'{chapter}-q{sum(x["chapter_id"]==chapter for x in questions)+1:03}', revision=1,
             chapter_id=chapter, unit_ids=[current['id']], source_pages=current['source_pages'], scope=scope,
             format='recall', category=category, importance='high', tags=[current['title']], quick_recall=quick,
             prompt=prompt, expected_answer=dict(style='chain' if '→' in answer else 'bullets',items=answer.split('|')),
             source_note=note)
    questions.append(obj)
    for point in answer.split('|'):
        if point not in current['recall_points']: current['recall_points'].append(point)
    return obj

def b(prompt, answers, category='data', note=''):
    if isinstance(answers,str): answers=[answers]
    for i in range(len(answers)): prompt=prompt.replace('___', '{{b'+str(i+1)+'}}',1)
    obj=q(prompt,'|'.join(answers),category,True,note=note)
    obj['format']='fill_blank'
    obj['blanks']=[dict(id=f'b{i+1}',answer=a,accepted_answers=[],label=f'Blank {i+1}',input_mode='text') for i,a in enumerate(answers)]
    for blank in obj['blanks']:
        try: float(blank['answer'].replace(',',''));blank['input_mode']='decimal'
        except ValueError: pass
    return obj

# Chapter 1 — physical PDF pages 1–39
unit(1,'Chapter architecture','synthesis')
q('Recall the major sections of the women chapter.','Status and historical perspective → reasons for inequality → safeguards → women’s organisations → role models and way forward','keywords')
unit(2,'Life cycle of discrimination','list')
q('Reconstruct the life cycle of discrimination from womb to tomb.','Foetus: sex selection, female foeticide|Infant: infanticide, malnutrition|Early age: neglected care and education, sexual abuse, physical violence|Adolescence: early marriage/pregnancy, sexual and domestic violence, dowry harassment, marital rape, son preference, desertion, maternal mortality|Older women/widows: witch-hunt, desertion, emotional/social/financial neglect, feminisation of elderly','list')
q('Why is discrimination described as “from womb to tomb”?','Sex selection before birth → deprivation and violence in childhood → marriage/reproductive coercion → neglect and widowhood in old age','reasoning')
q('Which forms of vulnerability are associated with older women and widows?','Witch-hunt|Desertion|Emotional, social and financial neglect|Feminisation of elderly: widowhood','keywords',True)
unit(3,'Crime frequency figures','data')
b('In the chapter’s crime-frequency figures, a woman is raped every ___ minutes; cruelty by in-laws occurs every ___ minutes; a dowry death is reported every ___ minutes.',['18','4','90'],note='Page attributes these figures to “NRCB and other credible sources”; no reference year is supplied.')
b('The material states that over ___ cases of crimes against women are lodged per hour across India.','50',note='No reference year supplied on the page.')
q('Recall the range of crimes included in the chapter’s hourly crime figure.','Rape, rape with murder|Dowry, acid attacks, suicide|Kidnapping, forced marriage, human trafficking|Online harassment','list')
unit([4,5],'Global Gender Gap Index','institution')
b('In the Global Gender Gap Index ___ edition, India ranks ___ out of ___ economies with a gender-parity score of ___%.',['2026','131','145','64.5'],'institution')
q('Recall the four dimensions of the Global Gender Gap Index and their indicators.','Economic participation/opportunity: LFPR, wage equality, estimated earned income|Educational attainment: literacy and primary/secondary/tertiary enrolment|Health and survival: sex ratio at birth, healthy life expectancy|Political empowerment: parliamentary/ministerial representation, years with female/male head of state','institution')
q('Why must women’s status be assessed across several dimensions?','Economic opportunity, education, health and political power are distinct dimensions → one aggregate score can conceal uneven parity','reasoning')
for label,s26,r26,s25,r25 in [('overall index','0.645','131','0.644','131'),('economic participation and opportunity','0.412','143','0.407','144'),('educational attainment','0.966','112','0.971','110'),('health and survival','0.956','136','0.954','143'),('political empowerment','0.245','67','0.245','69')]:
 b(f'In the page-5 gender-gap table, India’s {label} score/rank in 2026 are ___ / ___; in 2025 they are ___ / ___.',[s26,r26,s25,r25],note='Read from the embedded table; scores are on a 0–1 parity scale.')
q('What unevenness does the gender-gap radar chart show?','Education and health scores are close to parity|Economic participation and political empowerment scores are much lower','reasoning')
unit([6,15],'Women’s employment and unpaid work','data')
b('Female LFPR under PLFS 2025 (usual status) is ___%; the male LFPR stated on page 15 is ___%.',['40.0','79.1'])
b('Unpaid domestic work among participants in 2024 takes ___ minutes for women versus ___ minutes for men.',['289','88'])
b('According to PLFS 2025, salaried women’s average earnings equal ___% of men’s.','76')
q('How does unpaid care constrain women’s participation in paid work?','Unpaid domestic/care work consumes time → fewer paid-work opportunities → lower female labour-force participation','reasoning')
unit(6,'Representation and gender norms','data')
b('In 2024, ___ women were elected to the Lok Sabha out of ___ seats.',['74','543'])
b('About ___% of NSE-listed firms have a woman MD/CEO (2026); women hold ___% of board seats in the studied NSE top ___ (2025).',['5','20','200'])
b('The survey mentioned on page 6 dates to ___; about ___ of respondents in most studied locations disapproved of married women working when husbands earned well.',['2016','half'])
b('Census child sex ratio (ages 0–6) declined from ___ girls per 1,000 boys in 2001 to ___ in 2011.',['927','919'])
q('How can gender norms constrain women’s work even when household income is adequate?','Disapproval of married women working when husbands earn well → social restriction independent of financial need → lower participation','reasoning')
unit(7,'Women’s health, early marriage and education','data')
b('NFHS-5 (2019–21): ___% of women aged 15–49 are anaemic.','57')
b('SRS 2022–24: maternal mortality is ___ per 100,000 live births.','87')
b('NFHS-6 (2023–24): institutional births reached ___%; ___% of women aged 20–24 married before age 18.',['90.6','20.1'])
b('PLFS 2025 (age 7+): rural literacy is ___% for women and ___% for men; urban literacy is ___% for women and ___% for men.',['70.3','84.8','84.8','93.1'])
b('The page’s education figures show women at ___% of higher-education enrolment (AISHE 2023–24), ___% of PhD enrolment and ___% of undergraduate engineering enrolment.',['49.7','49.8','31.1'])
q('What contrast between education access and subject participation is visible in these figures?','Women are about half of higher-education/PhD enrolment|Their undergraduate engineering share is much lower','reasoning')
unit(8,'Vedic and medieval status','mechanism')
q('Reproduce the chapter’s explanation for the change from early to later Vedic women’s status.','Pastoral/nomadic economy → no economic surplus/private property → egalitarianism|Agriculture → division of labour → Grihapathi control over women','reasoning')
q('Recall the early Vedic women and institutions named in the material.','Gargi and Maitreyi → Sabhas and Samitis','keywords',True)
q('What practices and movements characterise the later Vedic and medieval discussion?','Stridharma, Pativratadharma, ritual purification and fasts|Bhakti and Lingayat movements: egalitarianism|Polygamy, purdah and talaq: continued prejudices|Mughal intervention in sati','keywords')
unit(9,'Colonial social reform','institution')
q('How did British education contribute to questioning women’s unequal status?','British education → emergence of a new elite → questioning existing social practices','reasoning')
q('Recall Raja Ram Mohan Roy and Brahmo Samaj’s reform concerns.','Sati|Female infanticide|Restrictions on widow remarriage|Illiteracy|Polygamy','list')
b('The Abolition of Sati Act is dated ___; the Widow Remarriage Act associated with Ishwar Chandra Vidyasagar is dated ___.',['1829','1856'],'institution')
q('Match the education-focused reform organisations with their figures.','Arya Samaj → Dayanand Saraswati|Prarthana Samaj → M.G. Ranade and R.G. Bhandarkar|Brahmo Samaj and Arya Samaj → mahila mandals','institution')
q('Recall the reform contributions of Veeresalingam, Karve, Tyabji and Ramabai.','Kandukuri Veeresalingam → widow remarriage|D.K. Karve → SNDT women’s university|Badruddin Tyabji/Muslim self-help association → girls’ schools, orphanages, nursing centres|Pandita Ramabai → Sharda Sadan for destitute widows','institution')
b('D.K. Karve established the SNDT women’s university in ___.','1916','institution')
unit(10,'Women in the nationalist movement','example')
q('Recall the women–organisation associations in the nationalist movement.','Sarala Devi → Bharat Stree Maha Mandal, Allahabad|Parvati Devi → Kanchi Mahila Parishad|Annie Besant → Theosophical Society|Women India Association → influence on government policies','institution')
q('Recall the contributions attributed to Kamala Devi Chattopadhyay, Rukmabai Raut and Mutthu Lakshmi Reddy.','Kamala Devi → first woman to contest elections; Civil Disobedience picketing|Rukmabai Raut → described as first Indian woman to have studied medicine|Mutthu Lakshmi Reddy → first woman nominated to Legislative Council; opposed Devadasi system and brothels','keywords',note='These are the descriptions used in the supplied slide.')
q('Which nationalist activities illustrate women’s direct political participation?','Sarojini Naidu → Dandi March and second Round Table Conference|Quit India → demonstrations, camps, Political Prisoners Relief Fund|INA → Rani Jhansi Regiment','keywords')
b('Anasuya Sarabhai led the Ahmedabad textile workers’ strike in ___.','1917')
q('Match the labour leaders to their constituencies.','Anasuya Sarabhai → Ahmedabad textile workers|Maniben Kara → socialist railway-worker leader|Parvati Bhore and Ushabai Dange → communist textile-worker leaders','keywords',True)
q('How did women’s participation in the freedom struggle influence their constitutional position, according to the chapter?','Political participation and collective struggle → recognition of women’s claims → constitutional voting rights and equality','reasoning')
unit(11,'Telangana movement and post-independence legislation','example')
b('The Telangana movement is dated ___–___; the Operation Polo mentioned on the slide took place in ___.',['1946','1951','1948'],note='The slide also says the movement ceased after Operation Polo; both statements are retained as source descriptions.')
q('Why did women participate in the Telangana movement?','Oppression by Nizam, Patils and Jagirdars|Exploitative Deshmukhs, Despandes and tax collectors|Vetti forced labour → exploitation of peasant girls','reasoning')
q('What did the women’s organisation and Andhra Vanita journal campaign against?','Child marriage|Restrictions on widow remarriage|Low wages','institution',True)
q('Recall the post-independence laws listed after the Telangana discussion.','Hindu Marriage Act|Hindu Succession Act|Dowry Prohibition Act|Equal Remuneration Act','institution')
unit(12,'Chipko and women’s livelihoods','example')
b('The Chipko discussion is situated in the ___; Gaura Devi led ___ village women to protect Reni forest.',['1970s','27'])
q('Recall Chipko’s five Fs and explain their connection to self-sufficiency.','Food, fodder, fuel, fibre, fertilizer → forest-linked livelihood needs → self-sufficiency','keywords')
q('Recall the location, leadership and tactics of Chipko described in this chapter.','Adwani, Tehri Garhwal district of UP|Adivasi women; later Sunderlal Bahuguna|Hugging trees and tying sacred thread|Gaura Devi stopped contractors/forest personnel entering Reni forest','keywords')
q('Why is Chipko relevant to women’s empowerment rather than only forest conservation?','Women defended forest-linked food, fodder, fuel, fibre and fertilizer → protection of livelihoods and self-sufficiency through collective action','reasoning')
unit(13,'Anti-rape and anti-dowry movements','example')
q('How did the priorities of elite women and poor/rural women differ in the 1970s discussion?','Elite: cultural activities and beauty pageants|Poor/rural: peasant conditions, wife beating, alcoholism, dowry, sexual harassment','relationship')
q('What triggered the anti-rape movement and what principle did it assert?','Mathura rape incident → protests and petitions → powerful people cannot violate poor/powerless people’s dignity and rights','reasoning')
q('Which organisation is associated with the anti-dowry movement, and what legal recognition followed?','Mahila Dakshata Samiti|Campaign against dowry, abetment to suicide and murder|Dowry demand recognised as potentially abetting suicide','institution')
unit(14,'Waves of feminism','concept')
q('Reconstruct the changing concerns of the four feminist waves in the material.','First: education, widows’ rights, child marriage; Ramabai, Savitribai Phule, Rukhmabai|Second: gender inequality, reproductive rights, violence, dowry; AIWC/university women’s studies centres|Third: intersectionality, gender justice, Dalit/marginalised rights|Fourth: online harassment, #MeToo','list')
b('The first feminist wave is dated ___ to the ___; the second to the ___–___; the third begins in the ___; the technology-era fourth follows ___.',['1850','1920s','1970s','80s','1980s','2000'])
q('Why does intersectionality expand the focus of the women’s movement?','Gender justice connected with Dalit and marginalised rights → attention to overlapping forms of disadvantage','reasoning')
unit([15,16],'Structural reasons for women’s inequality','mechanism')
q('How does preserving caste boundaries lead to control over women?','Caste boundary maintenance → control of property and sexuality → disinheritance, arranged marriage, child marriage|Purity associated with Anuloma and Pratiloma','reasoning')
q('Recall the three academic terms characterising the Indian family system.','Patriarchal|Patrilocal|Patrilineal','keywords',True)
q('How do marriage and family arrangements restrict women’s choices?','Husband and his parents make life choices|Pregnancy and child rearing → employment loss|Patriarchal, patrilocal, patrilineal family reinforces control','reasoning')
q('What religious and cultural mechanisms reinforce gender inequality in the chapter?','Son preference in funeral pyre and Shradha rituals|Discriminatory religious personal laws; example: triple talaq|Assumed gender roles and biases|Mass-media violence and normalised misogyny','keywords')
q('Why can gender inequality persist despite protective legislation?','Poor implementation of laws + patriarchal family/religious norms + economic restrictions + normalised misogyny → formal protection fails to transform lived status','reasoning')
q('How do caste and class overlap in women’s work restrictions?','Higher-caste restrictions overlap with class position|Upper-caste women engaged in unpaid domestic work|Control of women maintains caste boundaries','relationship')
unit(17,'Meaning and pillars of empowerment','concept')
q('Define women’s empowerment using the chapter’s core terms.','Equal power, authority and freedom|Eliminating disabilities/social restrictions|Making life choices and reaching full potential|Accessing socioeconomic resources','concept',True)
q('Recall the five pillars of empowerment and one intervention under each.','Education → safety, transport, toilets|Health → nutrition, delayed marriage, reproductive authority|Economic → safe work, skills, SHGs, equal pay|Sociocultural → parental/kin attitudes, #MeToo|Political → local-body reservation and parliamentary representation','list')
q('Why does the health pillar emphasise reproductive authority rather than mere fertility?','Empowerment requires women’s control over reproductive decisions → health and autonomy beyond simply managing fertility','reasoning')
b('The constitutional amendments named for political empowerment through local bodies are the ___ and ___.',['73rd','74th'],'institution')
unit(18,'From welfare to agency','institution')
q('How did the development approach to women change from welfare to empowerment?','Welfare → passive recipient of incentives|Development → health, education, employment; worker organisation/unionisation|Empowerment → SHGs, gender budgeting, enabling environment, local reservation|Later focus → gender equity and women’s agency','reasoning')
b('The welfare approach covers ___–___ and the first–fifth Plans; the development approach covers ___–___ and the sixth–seventh Plans; empowerment covers ___–___ in the slide.',['1951','1979','1980','1990','1992','2012'])
b('The Central Social Welfare Board was set up in ___; CSWI’s Towards Equality Report appeared in ___.',['1953','1974'],'institution')
q('Which committee produced Towards Equality, and what development-era schemes are named?','Committee on Status of Women in India (CSWI) → Towards Equality|STEP → Support to Training and Employment|AGP → Awareness Generation Programme for rural and poor women','institution')
q('What welfare-era services and later planning emphasis are recalled in the material?','Education/socioeconomic programmes|Working girls’ hostels and Short Stay Homes|Twelfth Plan onwards: gender equity, women’s agency and empowerment','institution')
unit(19,'Constitutional safeguards','institution')
q('Which values in the Preamble frame women’s constitutional safeguards?','Equality of status and opportunity|Dignity','institution',True)
for provision,article in [('equality to all','14'),('non-discrimination by the State on gender grounds','15(1)'),('affirmative action in favour of women','15(3)'),('equal opportunity for all','16'),('adequate means of livelihood equally for men and women','39(a)'),('equal pay for equal work','39(d)'),('just and humane work conditions and maternity relief','42'),('renouncing practices derogatory to women’s dignity','51(A)(e)')]:
 b(f'The constitutional provision for {provision} is Article ___.',article,'institution')
b('Reservation of Panchayat seats and chairpersons is mapped to Articles ___ and ___; Municipalities to ___ and ___.',['243D(3)','243D(4)','243T(3)','243T(4)'],'institution')
q('How do non-discrimination and affirmative action complement each other in the safeguards table?','Non-discrimination → equal treatment|Affirmative action → targeted support for women|Both advance substantive access and opportunity','reasoning')
unit(20,'BNS, family courts and interfaith marriage','institution')
for crime,section in [('punishment for rape','64'),('dowry death','80'),('cruelty by husband or relatives','85'),('voyeurism, stalking and insulting modesty (grouped)','77–79')]:
 b(f'The chapter maps {crime} to BNS section(s) ___.',section,'institution')
q('What women-friendly role is assigned to family courts?','Conciliators → women-friendly court procedures','institution',True)
b('The slide labels the Family Courts Act with the year ___.','1954','institution',note='Year reproduced exactly from the supplied source; not independently corrected.')
q('What property protection does the Special Marriage Act example illustrate?','Hindu woman marrying a Christian man retains rights to her family’s ancestral property under the amended Hindu Succession Act','institution')
unit(21,'Marriage, succession, triple talaq and trafficking safeguards','institution')
b('The Hindu Marriage Act is dated ___; the Hindu Succession Act ___, amended in ___; the Immoral Traffic Prevention Act ___.',['1955','1956','2005','1956'],'institution')
q('Recall the marital protections attributed to the Hindu Marriage Act.','Same lifestyle as husband|Freedom from torture at in-laws’ home|Husband’s financial support for child if wife cannot earn','institution')
q('What rights of daughters are stated under the amended Hindu Succession Act?','Equal rights in ancestral property|Equal distribution of joint-family property on intestate death','institution',True)
b('The chapter’s Muslim women protection law is dated ___; the reported fall in triple-talaq cases exceeds ___% within ___ year.',['2019','80','1'],'institution',note='Source labels the law “Muslim Women (Protection of Rights and Divorce) Act”; decline attributed to Ministry of Minority Affairs.')
q('What forms of instant triple talaq does the chapter describe as void and illegal?','Spoken|Written|Electronic|Any other manner','institution',True)
b('The Shayara Bano discussion cites Articles ___, ___ and ___ in holding instant triple talaq unconstitutional.',['14','15(1)','21'],'institution')
q('What is the purpose of the Immoral Traffic Prevention Act as given here?','Combat trafficking and commercial sexual exploitation','institution',True)
unit(22,'Maternity and dowry','institution')
b('The Maternity Benefit Act is dated ___; the ___ amendment provides up to ___ weeks, subject to conditions.',['1961','2017','26'],'institution')
q('Recall the workplaces and illness provision mentioned under maternity benefits.','Factories, mines, plantations and shops|Leave extension for illness due to pregnancy/delivery','institution')
b('The Dowry Prohibition Act is dated ___ and the slide states imprisonment up to ___ years.',['1961','5'],'institution')
q('What local implementation mechanism is named for dowry prohibition?','District-level dowry prohibition officers','institution',True)
b('The Telangana Kalyana Lakshmi/Shaadi Mubarak example gives ₹___ after age ___; the Sumangali example is located in Tamil Nadu in the ___.',['1,00,116','18','90s'])
q('Why are the Telangana marriage assistance and Sumangali examples criticised?','Marriage assistance → criticism of indirectly promoting dowry|Sumangali textile-mill work to save dowry → dowry + bonded/child labour double burden','reasoning')
unit(23,'MTP thresholds and categories','institution')
b('The MTP Act is dated ___; up to ___ weeks one RMP’s opinion is stated, while ___–___ weeks require two RMPs for specified categories.',['1971','20','20','24'],'institution')
q('Recall the specified categories for the intermediate MTP window in the slide.','Rape/incest survivors and minors|Marital-status change: widowhood/divorce|Physical disability or mental illness|Foetal abnormality cases|Humanitarian settings, disasters or emergencies','list')
b('Beyond ___ weeks, the slide allows termination for substantial foetal abnormalities on the opinion of a ___.',['24','Medical Board'],'institution')
q('How does the decision-making authority change across the MTP windows described here?','Earlier window → one RMP|Intermediate specified categories → two RMPs|Beyond threshold, substantial foetal abnormality → state/institution Medical Board','institution')
unit(24,'Child protection and marriage-age debate','institution')
b('POCSO is dated ___ and covers children below ___ years.',['2012','18'],'institution')
b('The slide labels the Prohibition of Child Marriage Act as ___ and gives legal marriage ages of ___ for girls and ___ for boys.',['2016','18','21'],'institution',note='The Act year is reproduced from this slide, not independently corrected.')
q('What implementation and support measures accompany child-marriage prohibition?','District child marriage prohibition officers|Support and rehabilitation|Awareness and education','institution')
q('Reconstruct the pros and concerns about raising girls’ marriage age stated in the slide.','Pros: empowerment; better maternal/infant health|Concerns: teenage pregnancy → unsafe abortions; longer perceived burden → further skewed sex ratio','reasoning')
unit(25,'Workplace harassment and sex selection','institution')
b('The workplace sexual-harassment prevention law is dated ___; the PCPNDT Act ___.',['2013','1994'],'institution')
q('What workplace coverage does the sexual-harassment law have in this material?','Public and private|Organised and unorganised|All workplaces','institution',True)
q('What two prohibitions are emphasised under PCPNDT?','Sex selection|Misuse of diagnostic techniques','institution',True)
unit(26,'Domestic violence and socialisation','mechanism')
b('The Domestic Violence Act discussed in the material is dated ___.','2005','institution')
q('Recall the social, economic and psychological causes of domestic violence.','Patriarchy and socialisation|Unemployment|Low self-esteem, jealousy, anger','list')
q('How can domestic violence reproduce itself through socialisation?','Children observe violence → learn to regard it as normal → normalisation of violent behaviour','reasoning')
q('What criticisms of domestic-violence enforcement are mentioned?','False cases|Subjective interpretation of verbal abuse and mental harassment','keywords',True)
unit(27,'Adultery and dignity','institution')
b('The repealed adultery provision is IPC Section ___; the dignity argument is linked to Article ___.',['497','21'],'institution')
q('Why does the chapter link repeal of the adultery provision to women’s dignity, and what legal relevance remains?','Violation of women’s dignity/right to life|Adultery remains a ground for divorce or cases of abetment to suicide, as described in the slide','reasoning')
unit(28,'Gender budgeting','institution')
q('Define gender budgeting and identify its nodal ministry.','Gender lens applied to public spending|Ministry of Women and Child Development','institution',True)
b('The Union Gender Budget Statement began in ___.','2005–06','institution')
b('Gender Budget Part A: ___% for women/girls; Part B: ___–___%; Part C: below ___%.',['100','30','99','30'],'institution')
b('In 2026–27 Budget Estimates, the Gender Budget is ₹___ lakh crore, or ___% of the Union Budget.',['5.01','9.37'])
q('How does gender budgeting connect public finance with empowerment?','Gender lens → identify spending for women/girls → resource allocation supports enabling conditions for empowerment','reasoning')
unit(29,'National Commission for Women','institution')
q('Recall NCW’s functions and civil-court-type powers.','Review legislation|Investigate women’s safeguards|Gender training programmes|Suo motu action|Summoning, requisitioning records, evidence and affidavits','institution')
q('Why can NCW’s influence remain limited despite its investigative powers?','Limited consultation in policy|Members insufficiently informed of changing trends|Restricted practical autonomy/selectivity|Non-binding recommendations|Financial constraints','reasoning')
unit([30,31,32],'Mission Shakti architecture','institution')
q('Distinguish Mission Shakti’s Sambal and Samarthya verticals.','Mission Shakti: safety and empowerment across life stages|Sambal: safety, protection, immediate support|Samarthya: care, services, empowerment','institution',True)
q('Reconstruct Sambal’s interventions and their roles.','One Stop Centres → medical/legal/police assistance, counselling, temporary shelter|Women Helpline → support/referral|Beti Bachao Beti Padhao → awareness/action for girl child|Nari Adalat → community-level collective dispute resolution|Nirbhaya Fund → finances centres and helpline','institution')
b('Women Helpline is ___ and offers free support for ___ hours a day.',['181','24'],'institution')
q('Reconstruct Samarthya’s services and their beneficiaries.','Shakti Sadan → shelter/rehabilitation for women in distress|Sakhi Niwas → working women’s safe accommodation|Palna → crèche care|PMMVY → maternity benefit for eligible pregnant/lactating women|SANKALP/Hub for Empowerment of Women → access to schemes/services','institution')
b('Palna provides crèche care from ___ months to ___ years of age.',['6','6'],'institution')
q('Why are safety interventions and care services both necessary in the chapter’s empowerment framework?','Immediate protection addresses violence/distress|Shelter, childcare and maternity support address care constraints|Together support women across life stages','reasoning')
unit([33,34],'PMMVY and maternal-support comparison','institution')
b('PMMVY 2.0: first living child receives ₹___ in ___ instalments; a second child, if a girl, receives ₹___ once.',['5,000','2','6,000'],'institution')
q('Recall PMMVY’s purpose, payment conditions and destination.','Partly compensate wage loss around childbirth|Antenatal checks|Birth registration|First immunisation cycle|Direct payment to woman’s account','institution')
q('Distinguish JSY, PMMVY and JSSK by purpose and type of benefit.','JSY/Janani Suraksha Yojana → encourage institutional delivery; cash incentive|PMMVY/Pradhan Mantri Matru Vandana Yojana → rest/maternal care; maternity cash benefit|JSSK/Janani Shishu Suraksha Karyakaram → remove costs at public facilities; free healthcare/transport','institution')
q('Recall JSSK’s beneficiaries and free services.','Pregnant women using public facilities and sick infants|Free delivery, medicines, tests, diet and transport|No cash payment','institution')
q('How do eligibility, conditions and administration differ across JSY, PMMVY and JSSK?','JSY: state-category rules; eligible-facility delivery; NHM; amount varies by state/rural–urban location|PMMVY: eligible pregnant/lactating women; care/registration/immunisation conditions; Mission Shakti–Samarthya|JSSK: public-facility users/sick infants; NHM; free services','institution')
q('Why are cash support and cost-free services complementary maternal-health interventions?','JSY incentivises facility delivery|PMMVY partly offsets wage loss/rest costs|JSSK removes healthcare/transport costs|Different barriers addressed by different benefits','reasoning')
unit(33,'Adolescent girls under POSHAN','institution')
b('The Scheme for Adolescent Girls under POSHAN 2.0 targets ages ___–___ years.',['14','18'],'institution')
q('Recall the geography and services of the Scheme for Adolescent Girls.','Aspirational Districts and northeastern states|Supplementary nutrition and iron–folic acid|Health checks and nutrition education|Referrals and skills-related support','institution')
unit(35,'Pre-independence organisations','institution')
for org,year in [('Women’s Indian Association','1917'),('National Council of Women in India','1923'),('All India Women’s Conference','1927'),('Satyashodhak Samaj','1873')]:
 b(f'The founding year stated for {org} is ___.',year,'institution')
q('Recall WIA’s location, key figures and contribution.','Adyar|Margaret Cousins and Dorothy Jinarajadasa; Annie Besant first president|Women’s education, suffrage and political representation','institution')
q('Distinguish NCWI and AIWC by figures and contribution.','NCWI → Lady Meherbai Tata; regional councils; women’s/children’s welfare|AIWC → Margaret Cousins; education, later child-marriage/legal reform','institution')
q('Which organisation founded in Pune challenged caste oppression and supported women’s education?','Satyashodhak Samaj → Jyotirao Phule → social equality and women’s education','institution',True)
unit(36,'SEWA and financial organisation','institution')
q('Who is associated with SEWA and Friends of Women’s World Banking, and who does SEWA mobilise?','Ela Bhatt, Gujarat|SEWA: informal-sector street vendors, domestic workers, agricultural labourers, artisans, self-employed women|Friends of Women’s World Banking: informal credit support and networks','institution')
q('How does SEWA link mobilisation to economic empowerment?','Organise informal workers → skills, credit/savings, income-generating activity support → stronger livelihoods|Policy advocacy → supportive regulations','reasoning')
unit(37,'Post-independence organisations and intersectionality','institution')
q('Recall AIDWA’s affiliation, concerns and campaign example.','CPI(M)|Women’s rights, education, employment, casteism, communalism, child rights, disaster aid|Campaign against HLL’s Fair and Lovely','institution')
q('What distinguishes YWCA India and All India Dalit Mahila Adhikar Manch?','YWCA → marginalised women regardless of age, caste or religion|Dalit Mahila Adhikar Manch → intersection of patriarchy, caste, culture, class and caste oppression','institution')
b('The YWCA slide describes ___ years of operation across the world.','125',note='Undated duration retained as a source statement, not a live age.')
q('How does Dalit women’s organisation connect with the third-wave feminist concern?','Patriarchy + caste + class/culture → overlapping oppression|Intersectionality and gender justice → attention to Dalit/marginalised rights','relationship')
unit(38,'International women’s institutions','institution')
q('Recall UN Women’s role.','Help intergovernmental bodies frame global standards|Support member states’ implementation|Global cooperation and coordination in women’s upliftment','institution',True)
q('What convention frames IWRAW’s work, and what does it address?','CEDAW → Convention on the Elimination of All Forms of Discrimination against Women|International human-rights treaty|IWRAW works on women’s human rights under it','institution',True)
unit(39,'Permanent commission in armed forces','concept')
q('What does permanent commission mean in the chapter?','A career in the armed forces until retirement','concept',True)
b('The chapter gives women’s shares in Army, Air Force and Navy as ___%, ___% and ___%; comparison countries exceed ___%.',['0.5','1','6.5','10'],note='No reference year is given on this slide.')
q('Reconstruct the arguments supporting women’s permanent commission and the concerns listed.','Support: equality; physical-criteria relaxation already exists for men from hilly regions and in IPS|Concerns: low acceptance of female bosses, infrastructure difficulties, vulnerability to harassment','reasoning')

# Chapter 2 — physical PDF pages 40–72
unit(40,'Population chapter architecture','synthesis')
q('Recall the population chapter’s main sections.','Introduction/theories → growth determinants → age/sex structure and growth phases → density/distribution → rapid-growth effects → control measures/models → delimitation and fertility concerns → way forward','keywords')
unit(41,'UNFPA population profile','data')
b('UNFPA 2025 estimates India’s population at ___ crore and describes it as the world’s ___ populous country.',['146.39','most'])
b('UNFPA 2025 age shares: ages 0–14 ___%; ages 15–64 ___%; ages 65+ ___%.',['24','68','7'])
b('UNFPA 2025: India’s TFR is ___ children per woman; life expectancy at birth is ___ years for males and ___ for females.',['1.9','71','74'])
b('The introduction names Census ___ as the world’s first ___ census.',['2027','digital'],'institution',note='Description retained from the supplied source.')
unit(42,'Demography and population education','concept')
q('Define demography.','Study of population size, composition and change through births, deaths and migration','concept',True)
q('Distinguish formal and social demography.','Formal → quantitative study of demographic processes|Social → social causes and consequences of population change','concept',True)
q('Recall the concerns covered by population education.','Population growth|Family planning|Reproductive health|Sustainable development|Gender equity|Population stabilisation','list')
q('Why does population education extend beyond birth control?','Population change connects to reproductive health, gender equity and sustainable development → awareness of broader causes/consequences from a young age','reasoning')
unit(43,'NFHS population, nutrition and autonomy indicators','data')
for indicator,value in [('population below age 15','25.5'),('stunting among children under five','29.3'),('wasting among children under five','19.0'),('underweight among children under five','31.8'),('fully vaccinated children aged 12–23 months','82.6'),('contraceptive use among currently married women','69.1'),('exclusive breastfeeding among infants under six months','55.8'),('women using their own bank or savings account','89.0')]:
 b(f'On page 43, NFHS-6 (2023–24) reports {indicator} at ___%.',value)
b('The NFHS-6 (2023–24) TFR given on page 43 is ___ children per woman.','2.0',note='UNFPA 2025/page 41 gives 1.9; recall each with its stated source.')
b('Anaemia among children aged 6–59 months is ___% under ___ (2019–21); page 43 says no NFHS-6 figure has been released.',['67.1','NFHS-5'])
q('Which updated NFHS-6 measure does the page explicitly say is not reported?','Overall sex ratio','keywords',True)
unit([43,44],'Undernutrition diagram','concept')
q('Distinguish wasting, stunting and underweight using the diagram.','Wasting → low weight for height|Stunting → low height for age|Underweight → low weight for age','concept',True)
q('Why should the three child-undernutrition figures not be treated as interchangeable?','Different reference dimensions: height-for-age, weight-for-height and weight-for-age → distinct indicators','reasoning')
unit(45,'Malthusian theory','concept')
b('T.R. Malthus’s prediction is dated ___.','1798')
q('Reproduce the Malthusian population–food reasoning chain.','Population grows geometrically; food production arithmetically → population outstrips subsistence resources → Malthusian catastrophe in the diagram','reasoning')
q('Distinguish preventive measures and positive checks in the Malthus discussion.','Preventive → delayed marriage, enforced celibacy|Positive → severe labour, epidemics, wars','concept',True)
q('What do the axes and intersecting curves in the Malthus diagram represent?','Time on horizontal axis; quantity on vertical axis|Population curve accelerates; resources increase linearly|Intersection marks subsistence limit/catastrophe','reasoning')
unit(46,'Demographic transition diagram','mechanism')
q('Reconstruct the five stages in the demographic transition diagram.','High stationary: high birth/death rates, low increase|Early expanding: death rate falls while births stay high|Late expanding: birth rate declines, growth slows|Low stationary: low birth/death rates|Possible declining stage: births below deaths, natural decrease','list')
q('Why does population expand rapidly when death rates fall before birth rates?','Deaths fall + births remain high → wider births–deaths gap → natural increase → rapid expansion','reasoning')
q('Why does a falling birth rate not necessarily mean immediate population decline in the diagram?','Births can remain above deaths while declining → positive natural increase persists → population still grows, more slowly','reasoning')
q('Recall the country examples attached to the five stages in this slide.','Stage 1 → Congo|Stage 2 → Iran|Stage 3 → India|Stage 4 → China|Stage 5 → Japan','keywords',note='These are illustrative slide labels, not independently updated country classifications.')
q('How do the age-structure shapes change across the demographic-transition illustration?','Early stages: broad base/young population|Later stages: base narrows, middle/older cohorts expand|Declining stage: smaller young cohorts relative to middle/older ages','reasoning')
unit([47,48],'Births, deaths and migration','concept')
q('Reconstruct the three population-change equations.','Natural increase = births − deaths|Net migration = immigrants − emigrants|Total change = births − deaths + net migration','keywords',True)
q('Define crude birth rate and crude death rate, retaining the denominator and period.','CBR: live births per 1,000 people per year|CDR: deaths per 1,000 people per year','concept',True)
b('SRS 2024: India’s CBR is ___ and CDR ___ per 1,000 people; natural increase is ___ per 1,000, excluding migration.',['18.3','6.4','11.9'])
q('Recall the factors influencing crude birth rate.','Age at marriage|Contraception|Women’s education and employment|Income|Child survival','list')
q('Recall the factors influencing crude death rate.','Population age structure|Healthcare, nutrition, sanitation|Epidemics|Conflict and disasters','list')
q('Why is natural increase insufficient to measure total population change?','Births minus deaths excludes migration|Immigration/emigration change the population too → add net migration','reasoning')
unit(49,'Infant mortality','concept')
b('IMR counts deaths before age ___ per ___ live births; SRS 2024 gives India’s IMR as ___.',['1','1,000','24'])
q('Recall the five groups of factors influencing infant mortality.','Prematurity and low birth weight|Birth complications/newborn infections|Limited timely newborn care|Incomplete immunisation/poor nutrition|Early pregnancy/inadequate maternal care','list')
q('How can access to maternal and newborn care influence infant survival?','Early pregnancy/inadequate maternal care + birth complications/infections → risk|Timely newborn care, nutrition and immunisation address these risks','reasoning')
unit(50,'Maternal mortality','concept')
b('MMR is maternal deaths per ___ live births; India’s SRS ___–___ value is ___.',['100,000','2022','2024','87'])
q('Recall the medical and access/autonomy factors affecting maternal mortality.','Haemorrhage, infection, high blood pressure|Obstructed labour, unsafe abortion|Anaemia/underlying illness|Delayed skilled/emergency care|Early pregnancy, limited reproductive autonomy','list')
q('Why does the maternal-mortality discussion require both healthcare and reproductive autonomy?','Medical complications require skilled/emergency care|Early pregnancy and restricted reproductive decisions create additional risk → health services and autonomy both matter','reasoning')
unit(51,'Fertility and replacement','concept')
q('Define TFR and replacement-level fertility as described in the material.','TFR: average children born to a woman over her lifetime|Replacement level: fertility at which one generation replaces the previous generation','concept',True)
b('Page 51 states current TFR as ___ and replacement-level fertility as ___.',['1.9','2.1'])
q('Recall the determinants of TFR in this chapter.','Age composition|Age at marriage/marriage duration|Sex ratio and migration|Religion and individual decisions|Income/living standard|Climate/environment|Joint-family system|Attitudes to vasectomy/tubectomy|Recreational facilities','list')
q('How does the chapter connect male migration into urban areas with lower fertility?','Male-selective migration → urban population has more men → altered sex composition → lower TFR, as stated in the slide','reasoning')
for year,value,projection in [('1950','6.18',False),('1980','4.60',False),('2021','1.91',False),('2050','1.29',True),('2100','1.04',True)]:
 b(f'The page-51 Lancet-attributed chart {"projects" if projection else "shows"} TFR for {year} at ___.',value,note='Chart values are separate from the current-value text; 2050 and 2100 are projections.')
q('What do the asterisks in the fertility chart distinguish?','Single asterisk → below replacement level of 2.1|Double asterisk → projection','keywords',True)
unit(52,'Sex ratio and dependency','concept')
q('Define sex ratio and distinguish it from child sex ratio.','Sex ratio: females per 1,000 males|Child sex ratio: girls per 1,000 boys in the 0–6 age group','concept',True)
b('Page 52 gives overall sex ratio as ___ under NFHS-5 and ___ under Census 2011; child sex ratio is ___.',['1020','940','919'],note='Census value retained exactly as written in the supplied slide.')
b('Page 52 gives Kerala’s sex ratio as ___ and Haryana’s as ___ females per 1,000 males.',['1084','877'])
b('The religious-group sex ratios on page 52 are ___ for Christians and ___ for Sikhs.',['1023','903'])
q('How does sex-selective migration explain the Kerala–Haryana contrast given in the material?','Kerala: male-selective outmigration → higher female/male ratio|Haryana: male-selective immigration → lower female/male ratio','reasoning')
q('Recall the regional and community pattern of sex ratio described in the slide.','Northwest below northeast and south|Christian and tribal belts have better sex ratios','keywords',True)
q('Reconstruct the dependency-ratio formula in the source.','(Population aged 0–14 + population above 65) ÷ population aged 15–64','concept',True,note='The slide writes “>65” in this formula and “65+” elsewhere; source wording retained.')
unit(53,'India’s demographic-growth phases','mechanism')
q('Reconstruct India’s four demographic-growth phases and their mechanisms.','Stagnant → high birth and death rates|Steady growth → death-rate decline; mortality-induced growth|Rapid high growth → population explosion|High growth with slowing signs → growth deceleration','list')
b('India’s four phases in the chapter span ___–___, ___–___, ___–___ and ___–___.',['1901','1921','1921','1951','1951','1981','1981','2011'])
b('The slide records negative growth of ___ in ___; highest growth of ___ in ___; and growth of ___ in 2011.',['-0.31','1921','2.48','1971','1.76'],note='Growth units are not explicitly printed alongside these text values; no unit is added.')
q('Why is the steady-growth phase described as mortality-induced growth?','Death rate declined considerably while births persisted → births exceeded deaths → steady population increase','reasoning')
b('In the page-53 historical graph, labelled CBR/CDR are ___/___ in 1901, ___/___ in 1921, ___/___ in 1971 and ___/___ at the 2021 endpoint.',['48','48','49','49','36','16','20','6'],note='Historical figure labels; caption says 1901–2017 although horizontal-axis endpoint reads 2021. Keep separate from SRS 2024 figures.')
q('What source split is given in the historical birth/death-rate chart caption?','1901–1961 → Mukherji (1976)|1971–2017 → annual statistical reports of Sample Registration System','institution')
q('What mechanism does the widening and later narrowing gap between CBR and CDR illustrate?','Death rate falls earlier → births–deaths gap expands → growth accelerates|Later birth-rate decline → gap narrows → growth slows','reasoning')
unit(54,'Density categories and map','data')
b('Text density bands (people per sq km): very high >___; high ___–___; moderate ___–___; low ___–___; extremely low <___.',['1000','500','1000','250','500','100','250','100'])
q('Reconstruct the very-high and high-density examples in the slide text.','Very high: Chandigarh, Puducherry, Daman & Diu; Delhi, Bihar, West Bengal|High: UP, Kerala, Tamil Nadu, Punjab, Haryana → agriculture/industry based','list')
q('Recall the moderate-density states listed in the text.','Gujarat, Karnataka, Andhra Pradesh, Tripura|Maharashtra, Jharkhand, Assam, Goa','list')
q('Recall the low and extremely-low density examples in the text.','Low: Meghalaya, Manipur, Himachal Pradesh, Nagaland, Chhattisgarh, Uttarakhand, Rajasthan, Madhya Pradesh|Extremely low: Arunachal Pradesh, Mizoram, Andaman & Nicobar Islands, Sikkim','list')
b('The embedded map legend uses bands below ___, ___–___, ___–___, ___–___ and above ___ people/sq km.',['100','100','300','300','500','550','1000','1000'],note='Map legend differs from slide text and visibly prints 550–1000; retained without harmonising.')
unit(55,'Factors shaping distribution','mechanism')
q('Recall the seven population-distribution factors.','Climate|Soil fertility|Altitude|Industries|Mineral resources|Urbanisation|Transport connectivity','list')
q('Explain the climate, soil and altitude links to population density given here.','Hot/dry deserts and high hills → low population|Rainy plains, alluvial north, deltas/coasts → high density|Kutch and Terai → low density in this slide','reasoning')
q('Reproduce the industry–migration–density chain and mineral-resource example.','Industry → jobs → immigration → higher population|Mineral resources → concentration in Chota Nagpur Plateau','reasoning')
b('The distribution slide describes over ___% of the population as agriculture-based.','60',note='No reference year/source is supplied for this figure.')
unit(56,'Rapid-growth consequences','mechanism')
b('The chapter states that ___% of world land area accommodates ___% of world population in India.',['2.4','17'],note='Undated figure from this slide, not updated to another population estimate.')
q('Recall the major effects of rapid population growth.','Unemployment, underemployment, disguised unemployment|Infrastructure pressure: overcrowding, slums, traffic|Land/natural-resource pressure|Inequality and poverty|Civil unrest','list')
q('How can rapid population growth create urban and social pressure?','Population increase → pressure on jobs, infrastructure and resources → overcrowding/slums/traffic and poverty/inequality → potential civil unrest','reasoning')
unit([57,58,59],'Demographic dividend and enabling conditions','concept')
q('Define demographic dividend and explain why it is a potential rather than an automatic benefit.','Rising working-age share relative to dependants → potential economic/social benefits|Requires human capital, skills, employment and women’s participation','concept')
b('The demographic-dividend slide gives working ages as ___–___, current share as ___%, and the golden window as ___–___ lasting ___ years.',['15','64','65','2018','2055','37'],note='Page 41 separately gives 68% under UNFPA 2025. Page 57’s current-share figure is undated.')
q('Recall the barriers to realising the demographic dividend and the unrest example.','Unemployed/frustrated youth → unrest; Arab Spring|Poor human capital|Low female LFPR|Skill gap','list')
q('Reconstruct the initiatives for demographic-dividend realisation.','Skill India and PMKVY|USTAAD → minority skill mentoring|Self Employment and Talent Utilization|Stand Up India/Start Up India|MOOCs → SWAYAM|Nai Roshni → women’s participation','institution')
q('Recall the additional measures proposed for the dividend.','NEP implementation and vocational training|Higher female LFPR|Fourth Industrial Revolution and AI opportunities|Entrepreneurship/startup support','list')
b('The education policy named for vocational training is NEP ___.','2020','institution')
q('How do skills and female workforce participation connect the women and population chapters?','Women’s care/work constraints reduce participation|Skills + enabling conditions + women’s employment → fuller use of working-age population → demographic-dividend potential','relationship')
unit(60,'Five-Year Plan population measures','institution')
q('Reconstruct the changing emphasis of the first five Plans on population.','First → programme, growth factors, planning knowledge, hospital integration|Second → education/research|Third → Copper T and independent family-planning department|Fourth → all birth-control methods|Fifth → population policy, maternal/child health/nutrition, marriage age, incentives and delimitation base','institution')
for plan,start,end in [('First','1951','1956'),('Second','1956','1961'),('Third','1961','1966'),('Fourth','1969','1974'),('Fifth','1974','1978')]:
 b(f'The {plan} Plan population-control discussion is dated ___–___.',[start,end],'institution')
b('The fifth-Plan discussion fixes delimitation on the Census of ___.','1971','institution')
unit(61,'Family welfare and National Health Policy','institution')
q('How did population policy shift after the 1970s and in the 1990s?','Post-1970s → family welfare|1990s → voluntary approach integrated with education, health, maternity/childcare, women’s rights, nutrition and anti-poverty programmes','reasoning')
b('The National Health Policy in the chapter is dated ___.','2017','institution')
b('NHP health-spending target: ___% of GDP by ___; the comparison value is ___% in 2022–23.',['2.5','2025','1.43'])
b('NHP life-expectancy target: ___ years by ___; the SRS 2020–24 comparison is ___ years.',['70','2025','70.6'])
b('NHP TFR target is ___ by ___; page 61 states the current value as ___.',['2.1','2025','1.9'])
b('NHP under-five mortality target is ___; the SRS 2024 comparison figure is ___.',['23','28'])
b('The HIV cascade target was ___–___–___ by 2020 and is stated as updated to ___–___–___.',['90','90','90','95','95','95'])
q('What do the three steps in the HIV cascade mean?','Know HIV status|Those knowing status receive ART|Those on ART achieve viral-load suppression','keywords',True)
b('The TB cure target is >___%; the cited TB Mukt Bharat treatment-success figure is ___%.',['85','90'])
b('NHP immunisation target: ___% by ___; NFHS-6 card-based full immunisation for children aged 12–23 months is ___%.',['90','2025','87.1'],note='Page 43 separately gives 82.6% without the card-based qualifier; do not merge the two.')
q('What health-workforce recommendation accompanies the NHP targets?','Increase density of paramedics and community health volunteers','institution',True)
unit(62,'National Population Policy objectives','institution')
b('National Population Policy ___ has a medium-term TFR target of ___ by ___ and a long-term stable-population target for ___.',['2000','2.1','2010','2045'],'institution')
q('Distinguish the immediate, medium-term and long-term NPP objectives.','Immediate → address unmet contraception needs|Medium → replacement-level TFR|Long → stable population','institution')
q('Recall the NPP measures beyond limiting family size.','Proper spacing between children|Free/compulsory education|Delayed marriage for adolescent girls|Information and counselling access','institution')
b('NPP recommends education until age ___ and targets by 2010: IMR ___ per 1,000, MMR ___ per lakh, institutional delivery ___%.',['14','30','100','80'])
q('Why does NPP combine contraception with education, marriage timing and counselling?','Fertility choices depend on knowledge, life opportunities and timing → services + education/counselling support spacing and family-size decisions','reasoning')
unit([63,64],'Current family-planning initiatives','institution')
q('What roles do Quality Assurance Committees and the family-planning indemnity scheme serve?','State/district committees → monitor service quality|National Family Planning Indemnity Scheme → insurance for unforeseen sterilisation deaths/complications','institution')
q('Recall the measures for awareness and increasing male participation.','Posters, billboards, audiovisuals → contraceptive choices and healthy timing/spacing|Non-scalpel vasectomy → less invasive, shorter recovery','institution')
q('What does the slide say about Minilap tubectomy provision?','MBBS qualification sufficient to perform it; no specialisation required, as stated in the source','institution',True)
q('Recall ASHAs’ family-planning roles and the postpartum method named.','Home delivery of contraceptives|Spacing counselling|Post Partum Intra Uterine Contraceptive Device|More reproductive/maternal/newborn/child-health counsellors','institution')
b('Mission Parivar Vikas coverage on page 64 includes ___ high-focus states and ___ northeastern states.',['7','6'],'institution')
q('How is family-planning funding allocated in the current-initiatives slide?','Approved through states’ Programme Implementation Plans according to their needs','institution',True)
q('How do delivery, counselling, quality assurance and indemnity address different family-planning barriers?','Home delivery → access|Counselling → informed choices/spacing|Quality assurance → service quality|Indemnity → protection against unforeseen complications','reasoning')
unit(65,'China’s policy sequence and ageing','data')
b('China’s one-child policy began in ___; universal two-child policy in ___; three-child permission in ___.',['1980','2016','2021'])
b('China’s population first declined in ___; end-2025 population was ___ crore, down ___ lakh from 2024.',['2022','140.49','33.9'])
b('In China in 2025, ages 60+ comprised ___% and ages 65+ ___%.',['23.0','15.9'])
q('What contrast does China’s policy sequence illustrate in the chapter’s broader population discussion?','Birth limitation → later permission for more births|Population decline and ageing → shift from controlling growth to fertility concerns','reasoning')
unit(66,'Indian state models','mechanism')
q('Reconstruct the Kerala model’s components.','Social reform → women/marginalised empowerment|Matrilineal system|Empowered village Panchayats|Outmigration → increased income|Active media|Male sterilisation: Ernakulam camp','list')
q('Distinguish Tamil Nadu, Himachal and Andhra Pradesh models.','TN → reform/small-family norm; early midday meals|Himachal → limited land, male outmigration, women’s empowerment; agriculture/apple orchards/horticulture|AP → cinema awareness ads; state population policy','relationship')
q('Reproduce the Himachal model’s empowerment chain.','Limited land → male outmigration → women’s empowerment|Agriculture, apple orchards and horticulture → economic empowerment','reasoning')
b('Andhra Pradesh’s state-level population policy is dated ___.','1997','institution')
q('Which common social mechanisms appear across the Indian state models?','Social reform and empowerment|Income/livelihood changes|Local governance|Media awareness|Small-family norms and male participation','relationship')
unit([67,70],'Delimitation, representation and federal concerns','institution')
b('States’ Lok Sabha seat shares remain broadly based on Census ___; the next milestone named is Census ___; women’s reservation is linked to the ___ Constitutional Amendment.',['1971','2027','106th'],'institution')
q('Why does the slide reject an automatic delimitation exercise simply in 2026?','Freeze does not expire into an automatic exercise|Next key milestone is Census 2027|Women’s reservation linked to post-census delimitation','reasoning')
q('Reconstruct the central delimitation trade-off.','More equal population per MP and manageable constituencies|Versus protecting political weight of states that achieved lower growth|Balance electoral equality with federal structure','reasoning')
q('How could changed state allocations affect reserved constituencies?','Changed state-seat allocation → possible changes in distribution/location of SC/ST reserved constituencies','reasoning')
q('Recall the arguments for readjustment and concerns about it.','For: reduce population-per-MP disparities; more MPs ease representation; reflect population changes|Concerns: some states lose relative seat share; family-planning success should not reduce political weight; federal balance','list')
unit([68,69],'Proposed delimitation illustrations','data')
b('The embedded news proposal uses Census ___ and proposes a maximum of ___ Lok Sabha seats.',['2011','850'],note='Proposal shown in an illustration, not enacted allocation; page 69 says the proposed Bill was voted down.')
b('The source’s September 2026 status note says the proposed Constitution (___ Amendment) Bill, 2026 was voted down in ___.',['131st','April'],'institution')
b('In the proposed 543-to-850-seat illustration, South’s share changes from ___% to ___%; Hindi heartland’s from ___% to ___%.',['24.3','20.7','38.1','43.1'],note='Hypothetical/proposed illustration; not current seat shares after an enacted reform.')
for region,increase,old,new in [('East','48.7','14.4','13.7'),('Hindi heartland','76.8','38.1','43.1'),('North-East','33.3','4.4','3.8'),('North-Non-Hindi','58.3','4.4','4.5'),('South','33.3','24.3','20.7'),('West','56.4','14.3','14.4')]:
 b(f'The proposed-delimitation table gives {region}: seat increase ___%, share of 543 seats ___%, share of 850 seats ___%.',[increase,old,new],note='Proposed illustration on page 69; not an enacted allocation.')
b('The proposed table’s grand-total seat increase is ___%.','56.5',note='Illustrative proposal only.')
b('The proposal map’s changes relative to a proportional increase are UP ___, Bihar ___, Rajasthan ___, J&K ___, West Bengal ___, Kerala ___ and Tamil Nadu ___.',['13','10','8','3','-2','-8','-11'],note='Map caption compares a proposed Census-2011-based exercise with proportional increases; negative figures are relative losses.')
q('Why can a state gain absolute seats yet lose its relative share in the proposed table?','Its seat increase can be smaller than the total increase → its proportion of all seats falls despite an absolute increase','reasoning')
unit(71,'State fertility-support developments','data')
b('Tamil Nadu’s G.O. dated ___ extended eligible government employees’ paid maternity leave for a third child from ___ weeks to ___ days.',['25 August 2026','12','365'])
b('Andhra Pradesh’s May 2026 announcement gives ₹___ for a third child and ₹___ for a fourth.',['30,000','40,000'])
b('Sikkim’s scheme gives ___ advance increment for a second child and ___ additional increment for a third; eligible births start from ___.',['one','one','1 January 2023'])
q('Distinguish the status and eligibility of the three fertility-support examples.','Tamil Nadu: G.O.; eligible woman government employee, third-child leave|AP: Chief Minister’s announcement of cash support|Sikkim: notified employee scheme; either spouse may claim increments','keywords')
unit(72,'Reproductive choice and family care','synthesis')
q('Reconstruct the chapter’s final policy shift.','Limiting births → supporting reproductive choice and family care|Address ageing + childcare + women’s employment together|Birth incentives alone may have limited impact|Resolve delimitation through representation policy, not fertility targets','list')
q('Why should delimitation concerns be addressed through representation policy rather than fertility targets?','Issue is allocation of political representation/federal balance → requires representation rules|Fertility policy should support reproductive choice and family care','reasoning')
q('Why might birth incentives alone be insufficient in the chapter’s framework?','Fertility connects to childcare, women’s work, reproductive choice and ageing → cash incentives alone do not address the wider family-care conditions','reasoning')

# Integrated recall: fewer prompts, concise architecture rather than full UPSC answers.
unit([1,2,8,15,17,18,19,29,30,35,39],'Women — chapter reconstruction','synthesis')
q('Reconstruct the women chapter in 10–15 keywords.','Life-cycle discrimination|Gender gap|Historical reform|Patriarchy|Caste/class|Unpaid care|Agency|Five pillars|Constitutional safeguards|Legal protection|Gender budgeting|NCW|Mission Shakti|Collective organisation|Permanent commission','synthesis',scope='chapter')
q('Reproduce the chapter’s main explanation of persistent inequality and the route to empowerment.','Patriarchy/caste/family norms → restricted choices, resources and work → unequal status|Rights + implementation + education/health + economic resources + collective organisation → agency and empowerment','synthesis',scope='chapter')
unit([6,7,15,16,17,22,32,33],'Women — care, work and agency','synthesis')
q('Connect unpaid care, marriage, maternity support and economic empowerment.','Unpaid care/pregnancy-child rearing → constrained paid work|Maternity benefits + crèches + safe accommodation/work + skills/equal pay → enabling conditions|Economic participation and reproductive authority strengthen agency','synthesis',scope='chapter')
q('Recall the main data anchors for women’s work, health, representation and education, with their sources.','PLFS 2025: female LFPR 40.0%, male 79.1%; women’s earnings 76% of men’s|2024 domestic work: 289 vs 88 minutes; Lok Sabha 74/543|NFHS-5: women’s anaemia 57%; SRS 2022–24 MMR 87|NFHS-6: institutional births 90.6%, early marriage 20.1%|AISHE 2023–24 higher education: 49.7% women','synthesis',scope='chapter',note='Integrated context reconstruction; exact-value practice is provided in Data Drill.')
unit([9,10,12,13,14,35,36,37,38],'Women — movements and organisation','synthesis')
q('Trace the changing logic of women’s collective action from reform to intersectionality.','Social reform: education, sati, widow remarriage|Nationalism: political/labour participation → equality/vote|Grassroots: forests, livelihoods, rape and dowry|Feminist waves: rights → reproductive justice → intersectionality → online harassment|Organisations: informal work, credit, Dalit rights and global standards','synthesis',scope='chapter')
q('Recall high-value examples and match each to the issue it illustrates.','Gargi/Maitreyi → early participation|Ramabai/Sharda Sadan → destitute widows|Gaura Devi/Chipko → collective livelihoods|Mathura → anti-rape mobilisation|Sumangali → dowry plus bonded/child labour|Ela Bhatt/SEWA → informal-worker organisation|Dalit Mahila Adhikar Manch → intersecting oppression','synthesis',scope='chapter')
unit([17,18,19,20,21,23,25,28,29,30,34],'Women — safeguards and contradictions','synthesis')
q('Reconstruct the institutional architecture of women’s empowerment.','Constitution: equality, non-discrimination, affirmative action, work/maternity, dignity, local representation|Laws: violence, marriage/property, maternity/reproduction, child protection, workplace and sex selection|CSWI/Towards Equality; NCW|Gender budgeting|Mission Shakti: Sambal/Samarthya|JSY–PMMVY–JSSK','synthesis',scope='chapter')
q('What contradictions recur across the women chapter?','Formal rights versus weak implementation|Education parity versus employment/leadership gaps|Protection versus limited practical autonomy|Marriage assistance versus dowry reinforcement|Permanent-commission equality versus institutional/social barriers','synthesis',scope='chapter')
unit([40,42,45,46,47,51,52,53,54,57,62,66,67,72],'Population — chapter reconstruction','synthesis')
q('Reconstruct the population chapter in 10–15 keywords.','Demography|Malthus|Transition|Birth/death rates|Migration|IMR/MMR|TFR|Replacement|Sex/dependency ratios|Growth phases|Density|Demographic dividend|Family welfare|Delimitation|Reproductive choice','synthesis',scope='chapter')
q('Reproduce the chapter’s main population-change reasoning chain.','Births − deaths + net migration → population change|Falling deaths before births → expansion|Later fertility decline → slower growth/ageing|Age structure + human capital + employment → dividend potential|Policy shifts from birth limits toward choice/family care','synthesis',scope='chapter')
unit([41,43,47,48,49,50,51,52,57,61,62],'Population — data and indicators','synthesis')
q('Recall the core population indicators with their denominator and source context.','UNFPA 2025: 146.39 crore; working-age share 68%; TFR 1.9|SRS 2024: CBR 18.3, CDR 6.4 per 1,000 people; IMR 24 per 1,000 births|SRS 2022–24: MMR 87 per 100,000 births|NFHS-6 page 43: TFR 2.0|NFHS-5 page 52: sex ratio 1020 per 1,000 males|Replacement TFR 2.1','synthesis',scope='chapter')
q('Which pairs of population figures must remain separated by source or qualifier?','TFR: UNFPA/current text 1.9 vs NFHS-6 2.0|Working-age share: UNFPA 68% vs undated dividend slide 65%|Full vaccination: page 43 82.6% vs card-based page 61 87.1%|Current SRS rates versus historical graph labels|Observed fertility versus future projections','synthesis',scope='chapter')
unit([15,17,47,49,50,51,57,59,62,66,72],'Population — women, health and dividend','synthesis')
q('Connect women’s empowerment, reproductive health, fertility and the demographic dividend.','Education/employment/autonomy affect fertility choices|Early pregnancy and poor care worsen maternal/infant risks|Counselling, contraception and spacing support choice|Skills + women’s participation → utilise working-age opportunity|Childcare and family care connect fertility concerns with employment','synthesis',scope='chapter')
q('Why can a favourable age structure still produce social unrest rather than a dividend?','Working-age opportunity without skills, human capital and jobs → frustrated/unemployed youth → unrest|Arab Spring example|Education, vocational skills, entrepreneurship and female participation are enabling conditions','synthesis',scope='chapter')
unit([60,61,62,63,64,65,66,71,72],'Population — policy evolution and models','synthesis')
q('Trace population policy from early Plans to present fertility concerns.','Early Plans: programmes/research/contraceptive methods|Fifth Plan: policy, maternal-child health, marriage age/incentives|Family welfare → voluntary integrated approach|NPP: contraception, replacement, stability|Current initiatives: access, quality, counselling|China decline/ageing and state incentives → reproductive choice/family care','synthesis',scope='chapter')
q('Compare the mechanisms of the China and Indian state models.','China: restrictive child-number policy → later relaxation amid ageing/decline|Kerala: reform, women’s empowerment, Panchayats, income/media/male sterilisation|TN: reform/small-family norm and meals|Himachal: outmigration/livelihood empowerment|AP: media and state policy','synthesis',scope='chapter')
unit([53,54,55,56,67,68,69,70,71,72],'Population — distribution and federal logic','synthesis')
q('Connect unequal population distribution to resources and representation.','Climate/soil/jobs/connectivity → uneven distribution|Concentration → infrastructure/resource pressure|Different growth rates → unequal population per MP|Seat readjustment → equality versus federal/family-planning concerns','synthesis',scope='chapter')
q('Reconstruct the delimitation debate and its relationship to fertility policy.','Population-based seats can improve population-per-MP equality|Lower-growth states fear reduced relative political weight|Proposed illustrations are not enacted allocations|Representation reform must balance federalism|Fertility policy should support choice/care, not political seat targets','synthesis',scope='chapter')

# Selective reverse associations, attached to original units and sorted into source order.
bytitle={u['title']:u for u in units}
current=bytitle['Gender budgeting']
b('The figure ₹5.01 lakh crore (2026–27 Budget Estimates) refers to the Union ___.','Gender Budget')
current=bytitle['NFHS population, nutrition and autonomy indicators']
b('The figure 2.0 children per woman in the NFHS-6 (2023–24) findings refers to ___.','Total Fertility Rate')['blanks'][0]['accepted_answers']=['TFR','total fertility rate']
current=bytitle['From welfare to agency']
b('Towards Equality (1974) is associated with the ___ committee.','Committee on Status of Women in India','institution')['blanks'][0]['accepted_answers']=['CSWI']
current=bytitle['Demographic dividend and enabling conditions']
b('The 2018–2055 window in the material is associated with India’s ___.','demographic dividend')

catalog=dict(schema_version=1,bank_version='2026-10-07-source-1',subjects=[dict(id='society',title='Society')],
 sources=[dict(id='society-lecture-03',title='Indian Society Lecture 03 PPT',private_filename='Indian Society Lecture 03 PPT (1).pdf',page_count=72)],
 chapters=[dict(id='women',number=1,subject_id='society',source_id='society-lecture-03',title='Role of Women and Women’s Organisations',page_start=1,page_end=39,bank_file='women.json',units_file='women-units.json'),dict(id='population',number=2,subject_id='society',source_id='society-lecture-03',title='Population and Associated Issues',page_start=40,page_end=72,bank_file='population.json',units_file='population-units.json')])

def save(path,obj): path.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
if __name__=='__main__':
 dest=ROOT/'questions';dest.mkdir(exist_ok=True)
 save(dest/'catalog.json',catalog)
 for ch in catalog['chapters']:
  qs=[x for x in questions if x['chapter_id']==ch['id']]
  qs.sort(key=lambda x:(x['scope']=='chapter',min(x['source_pages'])))
  save(dest/ch['bank_file'],qs)
  save(dest/ch['units_file'],[x for x in units if x['chapter_id']==ch['id']])
 audit=[]
 for page in range(1,73):
  audit.append(dict(page=page,chapter_id='women' if page<=39 else 'population',text_reviewed=True,visual_reviewed=True,
   unit_ids=[u['id'] for u in units if page in u['source_pages']],question_ids=[x['id'] for x in questions if page in x['source_pages']],
   notes={1:'Agenda used for chapter architecture; decorative photo not tested.',5:'Embedded score/rank table and radar inspected; extracted text alone misses them.',20:'Act year retained as source wording.',24:'Act year retained as source wording.',40:'Agenda used for architecture; decorative photo not tested.',44:'Image-only nutrition definitions inspected.',46:'Image-only transition curves and age shapes inspected.',51:'Lancet-attributed chart and projection footnotes inspected.',53:'Chart caption and endpoint years differ; question note records this.',54:'Text and embedded map legend use different bands; separately tested.',56:'Meme image inspected; app rating/download trivia omitted as irrelevant to population knowledge.',58:'Repeated initiatives merged with pages 57–59.',68:'News clipping describes a proposal, not enacted reform.',69:'Map, regional table, caption and status note inspected; proposed status preserved.'}.get(page,'Body text, emphasis, small notes and any illustrations inspected; decorative credits/logos omitted.')))
 save(dest/'page-audit.json',audit)
 print(f'{len(units)} knowledge units; {len(questions)} questions; {sum(x["format"]=="fill_blank" for x in questions)} fill-in questions')
 for ch in catalog['chapters']:print(ch['id'],sum(x['chapter_id']==ch['id'] for x in questions))
